 export const PDData = {
    organization_type : '',
    vehicle_id : '',
    make_id : '',
    model_id : '',
    _year : '',
    color_id : '',
    tow_hitch : '',
    trailer : '',
    lift_up_to : '',
    address_1 : '',
    state : '',
    city : '',
    zip_code : '',
    vehicle_photo : '',
    vehicle_inspection_form : '',
    vehicle_insurance : '',
    vehicle_registration : '',
    trailer_open : '',
    equipment_id : '',
    merchant : '',
    max_weight : '',
    bed_length : '',
    address_2 : ''
}
